from __future__ import annotations

from .installers.cloud import install_cloudflared, install_gcloud, install_supabase
from .installers.common import exists
from .installers.database import install_dbeaver, install_mysql, install_xampp
from .installers.foundation import install_gh, install_git, install_vscode
from .installers.javascript import (
    install_bun,
    install_claude,
    install_codex,
    install_node,
    install_pnpm,
    install_yarn,
)
from .installers.python_data import (
    install_jupyterlab,
    install_pipx,
    install_python_portable,
    install_uv,
)
from .installers.utilities import install_notepad, install_wget
from .models import Priority, Program

ECOSYSTEM_ORDER = [
    "Foundation",
    "JavaScript / TypeScript",
    "AI Developer CLI",
    "Python / Data",
    "Database",
    "Cloud / Platform",
    "Utilities",
]

PROGRAMS: list[Program] = [
    Program(
        id="git",
        name="Git",
        description="Version control",
        ecosystem="Foundation",
        priority=Priority.CORE,
        installer=install_git,
        installed=lambda: exists(r"git\cmd\git.exe"),
    ),
    Program(
        id="gh",
        name="GitHub CLI",
        description="GitHub from terminal",
        ecosystem="Foundation",
        priority=Priority.RECOMMENDED,
        installer=install_gh,
        installed=lambda: exists(r"github\bin\gh.exe"),
        dependencies=("git",),
    ),
    Program(
        id="vscode",
        name="Visual Studio Code",
        description="Code editor",
        ecosystem="Foundation",
        priority=Priority.CORE,
        installer=install_vscode,
        installed=lambda: exists(r"VisualCode\Code.exe"),
    ),
    Program(
        id="node",
        name="Node.js LTS",
        description="Node + npm + npx",
        ecosystem="JavaScript / TypeScript",
        priority=Priority.CORE,
        installer=install_node,
        installed=lambda: exists(r"node\node.exe"),
    ),
    Program(
        id="pnpm",
        name="pnpm",
        description="Fast package manager",
        ecosystem="JavaScript / TypeScript",
        priority=Priority.RECOMMENDED,
        installer=install_pnpm,
        installed=lambda: exists(r"pnpm\pnpm.exe"),
        dependencies=("node",),
    ),
    Program(
        id="bun",
        name="Bun",
        description="JS runtime + toolkit",
        ecosystem="JavaScript / TypeScript",
        priority=Priority.RECOMMENDED,
        installer=install_bun,
        installed=lambda: exists(r"bun\bun.exe"),
    ),
    Program(
        id="yarn",
        name="Yarn",
        description="Package manager",
        ecosystem="JavaScript / TypeScript",
        priority=Priority.OPTIONAL,
        installer=install_yarn,
        installed=lambda: exists(r"yarn\yarn.cmd"),
        dependencies=("node",),
    ),
    Program(
        id="codex",
        name="Codex CLI",
        description="OpenAI coding agent",
        ecosystem="AI Developer CLI",
        priority=Priority.RECOMMENDED,
        installer=install_codex,
        installed=lambda: exists(r"codex\codex.cmd") or exists(r"codex\codex.exe"),
        dependencies=("node",),
    ),
    Program(
        id="claude",
        name="Claude Code",
        description="Anthropic coding agent",
        ecosystem="AI Developer CLI",
        priority=Priority.RECOMMENDED,
        installer=install_claude,
        installed=lambda: exists(r"claude\claude.cmd") or exists(r"claude\claude.exe"),
        dependencies=("node",),
    ),
    Program(
        id="uv",
        name="uv",
        description="Python package manager",
        ecosystem="Python / Data",
        priority=Priority.CORE,
        installer=install_uv,
        installed=lambda: exists(r"uv\uv.exe"),
    ),
    Program(
        id="python",
        name="Python Portable",
        description="Managed CPython",
        ecosystem="Python / Data",
        priority=Priority.CORE,
        installer=install_python_portable,
        installed=lambda: exists(r"python\bin\python.exe"),
        dependencies=("uv",),
    ),
    Program(
        id="pipx",
        name="pipx",
        description="Isolated Python CLI apps",
        ecosystem="Python / Data",
        priority=Priority.OPTIONAL,
        installer=install_pipx,
        installed=lambda: exists(r"pipx\bin\pipx.exe"),
        dependencies=("uv", "python"),
    ),
    Program(
        id="jupyter",
        name="JupyterLab",
        description="Notebook + data IDE",
        ecosystem="Python / Data",
        priority=Priority.RECOMMENDED,
        installer=install_jupyterlab,
        installed=lambda: exists(r"jupyterlab\bin\jupyter-lab.exe"),
        dependencies=("uv", "python"),
    ),
    Program(
        id="mysql",
        name="MySQL",
        description="Database server binaries",
        ecosystem="Database",
        priority=Priority.RECOMMENDED,
        installer=install_mysql,
        installed=lambda: exists(r"mysql\bin\mysql.exe"),
    ),
    Program(
        id="dbeaver",
        name="DBeaver Community",
        description="Database GUI",
        ecosystem="Database",
        priority=Priority.RECOMMENDED,
        installer=install_dbeaver,
        installed=lambda: exists(r"dbeaver\dbeaver.exe"),
    ),
    Program(
        id="xampp",
        name="XAMPP",
        description="Apache + PHP + MariaDB",
        ecosystem="Database",
        priority=Priority.OPTIONAL,
        installer=install_xampp,
        installed=lambda: exists(r"xampp\xampp-control.exe"),
    ),
    Program(
        id="gcloud",
        name="Google Cloud CLI",
        description="GCP command line",
        ecosystem="Cloud / Platform",
        priority=Priority.RECOMMENDED,
        installer=install_gcloud,
        installed=lambda: exists(r"google-cloud\bin\gcloud.cmd"),
    ),
    Program(
        id="cloudflared",
        name="cloudflared",
        description="Cloudflare Tunnel",
        ecosystem="Cloud / Platform",
        priority=Priority.RECOMMENDED,
        installer=install_cloudflared,
        installed=lambda: exists(r"cloudflared\cloudflared.exe"),
    ),
    Program(
        id="supabase",
        name="Supabase CLI",
        description="Supabase development CLI",
        ecosystem="Cloud / Platform",
        priority=Priority.RECOMMENDED,
        installer=install_supabase,
        installed=lambda: exists(r"supabase\supabase.exe"),
    ),
    Program(
        id="notepad",
        name="Notepad++",
        description="Lightweight editor",
        ecosystem="Utilities",
        priority=Priority.OPTIONAL,
        installer=install_notepad,
        installed=lambda: exists(r"notepadpp\notepad++.exe"),
    ),
    Program(
        id="wget",
        name="wget",
        description="CLI downloader",
        ecosystem="Utilities",
        priority=Priority.OPTIONAL,
        installer=install_wget,
        installed=lambda: exists(r"wget\wget.exe"),
    ),
]

PROGRAM_BY_ID = {program.id: program for program in PROGRAMS}
